# Use the official Apache Airflow base image
FROM apache/airflow:2.7.2

# Install PostgreSQL client for connecting to the database
USER root
RUN apt-get update && apt-get install -y postgresql-client

# Create an entry point script
COPY script/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Switch back to the airflow user
USER airflow

# Specify the custom entry point script
ENTRYPOINT ["/entrypoint.sh"]
